// <auto-generated />
namespace Persona5Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initconfidants : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initconfidants));
        
        string IMigrationMetadata.Id
        {
            get { return "201903311726421_init-confidants"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
